<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="sonal-X556UQK" failures="0" tests="8" name="com.hubinternational.qa.testcases.SanityTest" time="0.006" errors="1" timestamp="2022-08-30T13:30:31 IST" skipped="7">
  <testcase classname="com.hubinternational.qa.testcases.SanityTest" name="hubLogoTest" time="0.000">
    <skipped/>
  </testcase> <!-- hubLogoTest -->
  <system-out/>
  <testcase classname="com.hubinternational.qa.testcases.SanityTest" name="setUp" time="0.006">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.hubinternational.qa.base.TestBase.initialization(TestBase.java:44)
at com.hubinternational.qa.testcases.SanityTest.setUp(SanityTest.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:617)
at org.testng.TestRunner.beforeRun(TestRunner.java:607)
at org.testng.TestRunner.run(TestRunner.java:578)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUp -->
  <system-out/>
  <testcase classname="com.hubinternational.qa.testcases.SanityTest" name="agribusinessPageTest" time="0.000">
    <skipped/>
  </testcase> <!-- agribusinessPageTest -->
  <system-out/>
  <testcase classname="com.hubinternational.qa.testcases.SanityTest" name="commercialPropertyPageTest" time="0.000">
    <skipped/>
  </testcase> <!-- commercialPropertyPageTest -->
  <system-out/>
  <testcase classname="com.hubinternational.qa.testcases.SanityTest" name="insightsPageTest" time="0.000">
    <skipped/>
  </testcase> <!-- insightsPageTest -->
  <system-out/>
  <testcase classname="com.hubinternational.qa.testcases.SanityTest" name="officesPageTest" time="0.000">
    <skipped/>
  </testcase> <!-- officesPageTest -->
  <system-out/>
  <testcase classname="com.hubinternational.qa.testcases.SanityTest" name="searchPageTest" time="0.000">
    <skipped/>
  </testcase> <!-- searchPageTest -->
  <system-out/>
  <testcase classname="com.hubinternational.qa.testcases.SanityTest" name="careersPageTest" time="0.000">
    <skipped/>
  </testcase> <!-- careersPageTest -->
  <system-out/>
</testsuite> <!-- com.hubinternational.qa.testcases.SanityTest -->
